# METEO

Meteo is a Java library/client for fetching data made public available by the Norwegian Meteorological Institute.

The main purpose of Meteo is to have a Java client that can fetch Weather data from the MET API and then present the
data within a Java API.

However, it is hard to interpret all the raw data provided by the MET API. Therefore Meteos also offers an extra library
that helps creating real weather reports (meteo-extras).



IMPORTANT
---------
http://api.met.no/#english
http://api.met.no/lisens_data.html
---------

The Norwegian Meteorological Institute holds ownership and Intellectual Property Rights to the data and products
produced by the institute (hereinafter referred to as PRODUCTS). Access and the right to use the selection of
PRODUCTS available here, shall not have the effect of transfer of such rights.

The Norwegian Meteorological Institute shall not be held liable for any consequences of the use made of the PRODUCTS.

The Norwegian Meteorological Institute does not guarantee regularity in updating of PRODUCTS, and changes in the
PRODUCTS may occur without notice.
