# METEO

Meteo is an Open-Source Java based library/client for handling weather data from http://api.met.no.

It mainly consists of two parts: A Java client and a library that helps you convert the raw data into
usable weather reports.

Please note that Meteo is in no way affiliated with the Norwegian Meteorological Institute
except for the fact that it use their API to provide you with weather data.

Meteo is developed and maintained by Amedia Utvikling AS. It is in use within all the Amedia sites (more than 70).
It mainly supports the services that Amedia needs at any given time. But we will consider adding other services as
well upon request.

## The MET terms of use

Make sure to read the http://api.met.no/conditions_service.html[Conditions for use of the service] from
the Norwegian Meteorological Institute.

Also make sure to read this http://api.met.no/license_data.html.

## Reverse proxying

As MET states in their terms of use, you must respect their cache headers. Meaning that you should only fetch one
resource one time within the TTL set by MET in each response.

The easiest way to achieve this is by installing a https://en.wikipedia.org/wiki/Reverse_proxy[Reverse Proxy]
like http://wiki.squid-cache.org/SquidFaq/ReverseProxy[Squid]. An alternative solution is to implement your own
https://github.com/amedia/meteo/blob/master/meteo-core/src/main/java/no/api/meteo/client/MeteoClient.java[MeteoClient]
that respects these requirements.

The https://github.com/amedia/meteo/blob/master/meteo-client/src/main/java/no/api/meteo/client/DefaultMeteoClient.java[default implementation]
of MeteoClient that ships with Meteo does not have any caching what so ever, but it does support configuring a proxy.

## The core library

This library is all about offering access to the raw MET data through a Java API. As stated earlier we have only
implemented support for the services that Amedia needs or that is requested/implemented by other users.


### Usage

You will find Meteo in the central maven repository: http://search.maven.org/#search|ga|1|a%3A%22meteo%22

For Maven you would add this to your pom:

[source, xml]
----
<dependency>
    <groupId>no.api.meteo</groupId>
    <artifactId>meteo-client</artifactId>
    <version>2.0.2</version>
</dependency>
----

If you want access to the extra helper libraries you must also add this to your pom:

[source, xml]
----
<dependency>
    <groupId>no.api.meteo</groupId>
    <artifactId>meteo-extras</artifactId>
    <version>2.0.2</version>
</dependency>
----

The Meteo core library is organized in a set of services where each service represents on of the services in the MET API.
Each service will need access to a Meteo client in order to be able to fetch data. You can either implement your own
client or use the default client found in the meteo-client package.

#### Creating a default client

[source, java]
----
MeteoClient client = new DefaultMeteoClient();
----

#### Use of services

At the moment we have a LocationForecast service and a Sunrise service implemented. The usage of these are pretty
 simple.

[source, java]
----
LocationforecastLTSService service = LocationforecastLTSService(client);
try {
    MeteoData<Sunrise> fetchContent(longitude, latitude, date);
} catch (MeteoException e) {
    // Handle exception.
}
----




