//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.17 at 03:24:40 PM CET 
//


package no.api.meteo.jaxb.sunrise.v1_1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The location the data is wanted for.  Latitude(lat) and
 *         longitude(lon) are both given in decimal degrees.  East and
 *         North are positive values, West and South negative.
 *       
 * 
 * <p>Java class for locationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sun" type="{}sunType"/>
 *         &lt;element name="moon" type="{}moonType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="latitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationType", propOrder = {
    "sun",
    "moon"
})
public class LocationType {

    @XmlElement(required = true)
    protected SunType sun;
    @XmlElement(required = true)
    protected MoonType moon;
    @XmlAttribute(name = "latitude", required = true)
    protected BigDecimal latitude;
    @XmlAttribute(name = "longitude", required = true)
    protected BigDecimal longitude;

    /**
     * Gets the value of the sun property.
     * 
     * @return
     *     possible object is
     *     {@link SunType }
     *     
     */
    public SunType getSun() {
        return sun;
    }

    /**
     * Sets the value of the sun property.
     * 
     * @param value
     *     allowed object is
     *     {@link SunType }
     *     
     */
    public void setSun(SunType value) {
        this.sun = value;
    }

    /**
     * Gets the value of the moon property.
     * 
     * @return
     *     possible object is
     *     {@link MoonType }
     *     
     */
    public MoonType getMoon() {
        return moon;
    }

    /**
     * Sets the value of the moon property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoonType }
     *     
     */
    public void setMoon(MoonType value) {
        this.moon = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

}
