//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.17 at 03:24:40 PM CET 
//


package no.api.meteo.jaxb.sunrise.v1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 	Moon related information, all timestamps are given in UTC.  It
 * 	will return 0, 1 or 2 rise and set events.  In the case with 2
 * 	rises or sets, the first set/rise is in the attribute
 * 	set/rise, the second event will be in the attribue
 * 	set_next/rise_next.
 *       
 * 
 * <p>Java class for moonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="moonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="error" type="{}errorType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rise" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="rise_next" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="never_rise" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="set" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="set_next" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="never_set" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="phase" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="New moon"/>
 *             &lt;enumeration value="Waxing crescent"/>
 *             &lt;enumeration value="First quarter"/>
 *             &lt;enumeration value="Waxing gibbous"/>
 *             &lt;enumeration value="Full moon"/>
 *             &lt;enumeration value="Waning gibbous"/>
 *             &lt;enumeration value="Third quarter"/>
 *             &lt;enumeration value="Waning crescent"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "moonType", propOrder = {
    "error"
})
public class MoonType {

    protected ErrorType error;
    @XmlAttribute(name = "rise")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar rise;
    @XmlAttribute(name = "rise_next")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar riseNext;
    @XmlAttribute(name = "never_rise")
    protected Boolean neverRise;
    @XmlAttribute(name = "set")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar set;
    @XmlAttribute(name = "set_next")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar setNext;
    @XmlAttribute(name = "never_set")
    protected Boolean neverSet;
    @XmlAttribute(name = "phase", required = true)
    protected String phase;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

    /**
     * Gets the value of the rise property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRise() {
        return rise;
    }

    /**
     * Sets the value of the rise property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRise(XMLGregorianCalendar value) {
        this.rise = value;
    }

    /**
     * Gets the value of the riseNext property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRiseNext() {
        return riseNext;
    }

    /**
     * Sets the value of the riseNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRiseNext(XMLGregorianCalendar value) {
        this.riseNext = value;
    }

    /**
     * Gets the value of the neverRise property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNeverRise() {
        return neverRise;
    }

    /**
     * Sets the value of the neverRise property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeverRise(Boolean value) {
        this.neverRise = value;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSet(XMLGregorianCalendar value) {
        this.set = value;
    }

    /**
     * Gets the value of the setNext property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSetNext() {
        return setNext;
    }

    /**
     * Sets the value of the setNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSetNext(XMLGregorianCalendar value) {
        this.setNext = value;
    }

    /**
     * Gets the value of the neverSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNeverSet() {
        return neverSet;
    }

    /**
     * Sets the value of the neverSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeverSet(Boolean value) {
        this.neverSet = value;
    }

    /**
     * Gets the value of the phase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase(String value) {
        this.phase = value;
    }

}
