//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.17 at 03:24:42 PM CET 
//


package no.api.meteo.jaxb.textlocation.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for proddesc_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="proddesc_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="prodname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "proddesc_type")
public class ProddescType {

    @XmlAttribute(name = "prodname", required = true)
    protected String prodname;

    /**
     * Gets the value of the prodname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdname() {
        return prodname;
    }

    /**
     * Sets the value of the prodname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdname(String value) {
        this.prodname = value;
    }

}
